"""The epoch each building actually unlocks in.

Generated by tools/gen_building_epochs.py from a running game. Don't
edit by hand.

`dbobjects.dat` disagrees, and not by a constant — it reads one higher
for most buildings and two higher for the Temple. The number here is
`node + 0x14`, which is what the availability predicate compares
against the current epoch, so it's what the game gates on.
"""

BUILDING_EPOCH: dict[str, int] = {
    "Airport": 9,
    "Archery Range": 1,
    "Barracks": 0,
    "Capitol": 0,
    "Cyber Factory": 12,
    "Cyber Laboratory": 12,
    "Dock": 1,
    "Fortress": 2,
    "Granary": 2,
    "Hospital": 2,
    "House": 0,
    "Navy Yard": 9,
    "Pyramid": 0,
    "Settlement": 0,
    "Siege Factory": 3,
    "Space Dock": 14,
    "Space Turret": 14,
    "Stable": 2,
    "Tank Factory": 9,
    "Temple": 0,
    "Town Center": 0,
    "University": 2,
}
