"""Which building produces each unit family.

Generated by tools/gen_producers.py from the technology_tree.pdf that
ships with the game. Don't edit by hand.

A family is produced by ANY of the buildings listed for it, so the rule
built from this is a disjunction. Without it, generation could hide a
building unlock behind a check that needs that very building.
"""

UNIT_FAMILY_PRODUCERS: dict[str, tuple[str, ...]] = {
    "Tank": ("Tank Factory",),
    "Anti Tank": ("Siege Factory",),
    "Aircraft": ("Airport",),
    "Priest": ("Temple",),
    "Submarine": ("Dock", "Navy Yard",),
    "Hero": ("Capitol", "Town Center",),
    "Ship": ("Dock", "Navy Yard",),
    "Spear Thrower": ("Archery Range",),
    "Machines": ("Siege Factory",),
    "Human Musket": ("Barracks",),
    "Human Sword": ("Barracks",),
    "Mounted Archer": ("Stable",),
    "Lancer": ("Stable",),
    "Helicopter": ("Airport",),
    "Curiassier": ("Stable",),
    "Bomber": ("Airport",),
    "Battleship": ("Dock", "Navy Yard",),
    "Human": ("Barracks",),
    "Mech - Minotaur": ("Cyber Factory", "Cyber Laboratory",),
    "Mech - Medium": ("Cyber Factory", "Cyber Laboratory",),
    "Mech - Zeus": ("Cyber Factory", "Cyber Laboratory",),
    "Mech - Cyclops": ("Cyber Factory", "Cyber Laboratory",),
    "Human Archer": ("Archery Range",),
    "Ram": ("Siege Factory",),
    "Siege": ("Barracks", "Siege Factory",),
    "Land AA": ("Barracks", "Tank Factory",),
    "Mech - Apollo": ("Cyber Factory", "Cyber Laboratory",),
    "Tank - Strong": ("Tank Factory",),
    "Citizen": ("Capitol", "Town Center",),
    "Human Machine Gun": ("Barracks",),
    "Medieval Field Weapon": ("Siege Factory",),
    "Human Spear": ("Barracks",),
    "Mounted Spear": ("Stable",),
    "Atomic Bomber": ("Airport",),
    "Mech - Underwater": ("Cyber Factory", "Cyber Laboratory",),
    "Viking": ("Barracks",),
    "Ship Galley": ("Dock", "Navy Yard",),
    "War Elephant": ("Stable",),
    "Elephant Archer": ("Archery Range",),
    "Aircraft Carrier": ("Dock", "Navy Yard",),
    "Elite Guard": ("Barracks",),
    "Artillery": ("Siege Factory",),
    "Cavalry Archer": ("Archery Range",),
    "Spaceship": ("Space Dock",),
    "Space Fighter": ("Space Dock",),
    "Space Corvette": ("Space Dock",),
}
