"""Which building produces each unit family.

Generated by tools/gen_producers.py from the technology_tree.pdf that
ships with the game; do not edit by hand.

A family is produced by ANY of the buildings listed for it, so the rule
built from this is a disjunction. Without it, generation could hide a
building unlock behind a check that needs that very building.
"""

UNIT_FAMILY_PRODUCERS: dict[str, tuple[str, ...]] = {
    "Citizen": ("Capitol", "Settlement", "Town Center",),
    "Human Sword": ("Barracks",),
    "Human Spear": ("Barracks",),
    "Human Archer": ("Archery Range",),
    "Human Musket": ("Barracks",),
    "Human Machine Gun": ("Barracks",),
    "Spear Thrower": ("Archery Range",),
    "Mounted Archer": ("Stable",),
    "Mounted Spear": ("Stable",),
    "Lancer": ("Stable",),
    "Curiassier": ("Stable",),
    "Siege": ("Barracks", "Siege Factory",),
    "Ram": ("Siege Factory",),
    "Machines": ("Siege Factory",),
    "Medieval Field Weapon": ("Siege Factory",),
    "Tank": ("Tank Factory",),
    "Tank - Strong": ("Tank Factory",),
    "Anti Tank": ("Siege Factory",),
    "Land AA": ("Barracks", "Tank Factory",),
    "Aircraft": ("Airport",),
    "Bomber": ("Airport",),
    "Atomic Bomber": ("Airport",),
    "Helicopter": ("Airport", "Capitol", "Settlement", "Town Center",),
    "Ship": ("Dock", "Navy Yard",),
    "Battleship": ("Dock", "Navy Yard",),
    "Submarine": ("Dock", "Navy Yard",),
    "Priest": ("Temple",),
}
