"""Every technology: the epoch it appears in, and where it is researched.

Generated by tools/gen_technologies.py. Don't edit by hand. The names,
buildings and epochs come from tools/data/technologies.tsv, the button
textures from a running game.

The texture is how the client finds a technology's node, and `node+0x04`
is the byte the game sets when it has been researched — measured, twice,
by snapshotting every node and researching exactly one thing.

Only five buildings research anything and the Capitol is never locked, so
a technology's building requirement only bites for the other four.
"""

# name -> (epoch, building, button texture, node epoch, effect id)
#
# The node epoch is carried because a texture isn't unique. Every wall
# and tower upgrade shares `but_upgrade wall and tower`, and only the
# epoch on the node tells the seven apart — keying lookups on the
# texture alone silently collapsed six of them.
TECHNOLOGIES: dict[str, tuple[int, str, str, int]] = {
    "Mysticism": (0, "Temple", "but_mysticism_01", 0, 1078),
    "Sandals": (0, "Temple", "but_sandals_01", 0, 1079),
    "Ancestor Worship": (1, "Temple", "but_ancestorworship_02", 1, 2051),
    "Ceremonial Burial": (1, "Temple", "but_ceremonial burial_02", 1, 2052),
    "Hafted Tools": (1, "Capitol", "but_hafts_02", 1, 2050),
    "Shamanism": (1, "Temple", "but_shamanism_02", 1, 2053),
    "Fine-Edged Tools": (2, "Capitol", "but_fineflakedtools_02", 2, 3062),
    "Hand Axe": (2, "Capitol", "but_handaxe_01", 2, 3061),
    "Herbal Medicines": (2, "Hospital", "but_herbal medicines_03", 2, 3064),
    "Irrigation": (2, "Granary", "but_irrigation_04", 2, 3052),
    "Mythology": (2, "Temple", "but_mythology_03", 2, 3070),
    "Oil Lamp": (2, "University", "but_oillamp_03", 2, 3055),
    "Polytheism": (2, "Temple", "but_polytheism_03", 2, 3071),
    "Upgrade to Wall & Tower - Copper": (2, "Capitol", "but_upgrade wall and tower", 2, 3051),
    "Hardened Chisel": (3, "Capitol", "but_hardened chisel", 3, 4092),
    "Hippocratic Oath": (3, "Hospital", "but_hippocratic oath_04", 3, 4008),
    "Metal Casting": (3, "Capitol", "but_metal casting_03", 3, 4091),
    "Monotheism": (3, "Temple", "but_monotheism_04", 3, 4060),
    "Oracle": (3, "Temple", "but_oracle_04", 3, 4011),
    "Philosophy": (3, "University", "but_philosophy_04", 3, 4006),
    "Pulley": (3, "University", "but_pulley_04", 3, 4059),
    "Upgrade to Wall & Tower - Bronze": (3, "Capitol", "but_upgrade wall and tower", 3, 4061),
    "Cofferdam": (4, "University", "but_coffer dam_05", 4, 5088),
    "Commercial Law": (4, "University", "but_commercial law_05", 4, 5051),
    "Comparative Anatomy": (4, "Hospital", "but_comparitive anatomy_05", 4, 5087),
    "Excommunication": (4, "Temple", "but_excommunication_05", 4, 5061),
    "Falconry": (4, "Capitol", "but_falconry_05", 4, 5020),
    "Iron Saw": (4, "Capitol", "but_saw_04", 4, 5021),
    "Pharmacy": (4, "Hospital", "but_pharmacy_05", 4, 5006),
    "Prophecy": (4, "Temple", "but_prophecy_05", 4, 5060),
    "Sainthood": (4, "Temple", "but_sainthood_05", 4, 5013),
    "Sanitation": (4, "Hospital", "but_sanitation_05", 4, 5086),
    "Amalgamation": (5, "Capitol", "but_amalgamation_06", 5, 6050),
    "Bulls-Eye Lantern": (5, "University", "but_bullseye lantern_06", 5, 6003),
    "Crusades": (5, "Temple", "but_crusades_06", 5, 6061),
    "Indulgences": (5, "Temple", "but_indulgences_06", 5, 6060),
    "Inquisition": (5, "Temple", "but_inquisition_06", 5, 6018),
    "Law Schools": (5, "University", "but_law schools_06", 5, 6002),
    "Shaft Mining": (5, "Capitol", "but_shaft mining_08", 5, 6093),
    "Upgrade to Wall & Tower - Medieval": (5, "Capitol", "but_upgrade wall and tower", 5, 6051),
    "Wheeled Plow": (5, "Granary", "but_wheeled drawn plow_06", 5, 6070),
    "Astrology": (6, "Temple", "but_astrology_07", 6, 7061),
    "Human Anatomy": (6, "Hospital", "but_human anatomy_06", 6, 7086),
    "Printing Press": (6, "Temple", "but_printing press_07", 6, 7083),
    "Quarantine": (6, "Hospital", "but_quarantine_07", 6, 7002),
    "Tarot": (6, "Temple", "but_tarot_07", 6, 7060),
    "Windlass": (6, "Capitol", "but_windlass_08", 6, 7064),
    "Chemical Drugs": (7, "Hospital", "but_chemical drugs_08", 7, 8006),
    "Dry Dock": (7, "University", "but_drydock_08", 7, 8077),
    "Forestry": (7, "Capitol", "but_forestry_07", 7, 8075),
    "Land Conservation": (7, "Capitol", "but_land conservation_08t", 7, 8011),
    "Missionaries": (7, "Temple", "but_missionaries_08", 7, 8085),
    "Occultism": (7, "Temple", "but_occultism_08", 7, 8061),
    "Orthopedics": (7, "Hospital", "but_orthopedics_08", 7, 8005),
    "Reformation": (7, "Temple", "but_reformation_08", 7, 8060),
    "Scientific Method": (7, "University", "but_scientific method_08", 7, 8012),
    "Strengthened Concrete": (7, "University", "but_reinforced concrete_08", 7, 8013),
    "Upgrade to Wall & Tower - Imperial": (7, "Capitol", "but_upgrade wall and tower", 7, 8070),
    "Anesthesia": (8, "Hospital", "but_anesthesia_09", 8, 9010),
    "Enclosure": (8, "Granary", "but_enclosure_08", 8, 9022),
    "Gas Lamps": (8, "University", "but_gaslamp_09", 8, 9012),
    "Mining Explosives": (8, "Capitol", "but_explosives_07", 8, 9030),
    "Pasteurization": (8, "Hospital", "but_pasteurization_09", 8, 9062),
    "Religious Tolerance": (8, "Temple", "but_religious tolerance_09", 8, 9061),
    "Steam Engine": (8, "Capitol", "but_steam engine_09", 8, 9000),
    "Sunday School": (8, "Temple", "but_sundayschool_09", 8, 9060),
    "Civil Liberties": (9, "University", "but_civil liberties_10", 9, 10000),
    "Hammer Drilling Rigs": (9, "Capitol", "but_hammer drilling rig_11", 9, 10066),
    "Radio Services": (9, "Temple", "but_radioservices_10", 9, 10060),
    "Upgrade to Wall & Tower - Concrete": (9, "Capitol", "but_upgrade wall and tower", 9, 10053),
    "Vitamins": (9, "Hospital", "but_vitamins_10", 9, 10061),
    "Building Codes": (10, "University", "but_building codes_12", 11, 12005),
    "DNA Research": (10, "Hospital", "but_dna research_11", 10, 11024),
    "Environmental Law": (10, "Capitol", "but_environmental laws_11", 10, 11032),
    "Mechanized Logging": (10, "Capitol", "but_mechanized logging_10", 10, 11033),
    "Scuba Repairs": (10, "University", "but_scuba repairs_11", 10, 11045),
    "Televangelism": (10, "Temple", "but_televangelism_11", 10, 11061),
    "Vaccinations": (10, "Hospital", "but_vaccinations_11", 10, 11062),
    "Basic Oxygen Furnace": (11, "Capitol", "but_basic oxygen furnace_11", 11, 12058),
    "Hydraulic Mining": (11, "Capitol", "but_hydraulic mining_11", 11, 12059),
    "Magnetic Resonance Imaging": (11, "Hospital", "but_mri_12", 11, 12051),
    "Pesticides": (11, "Granary", "but_chemical pesticides_10", 11, 12012),
    "Religious Resurgence": (11, "Temple", "but_religiousresurgence_12", 11, 12060),
    "Digital Library": (12, "University", "but_digital library_13", 12, 13005),
    "Genetic Engineering": (12, "Hospital", "but_genetic engineering_13", 12, 13071),
    "Self Sufficiency": (12, "Capitol", "but_self sufficiency movement_14", 12, 13025),
    "Upgrade to Wall & Tower - Laser": (12, "Capitol", "but_upgrade wall and tower", 12, 13051),
    "Virtual Services": (12, "Temple", "but_virtualservices_13", 12, 13060),
    "Anti-Aging Pill": (13, "Hospital", "but_antiaging pill_14", 13, 14001),
    "Atom Manipulation": (13, "Capitol", "but_atom manipulation_14", 13, 14028),
    "Core Mining": (13, "Capitol", "but_core mining_14", 13, 14029),
    "Cybernetics": (13, "Hospital", "but_cybernetics_14", 13, 14000),
    "Hydroponics": (13, "Granary", "but_hydroponics_13", 13, 14002),
    "Mind Control": (13, "Temple", "but_mind control_14", 13, 14050),
    "Damage Control": (14, "Hospital", "but_damagecontrol", 14, 15025),
    "Faith Healing": (14, "Temple", "but_faithhealing_10t", 14, 15022),
    "Quantum Theology": (14, "Temple", "but_quantumtheology_15t", 14, 15023),
    "Robotic Farm": (14, "Granary", "but_farm_15t", 14, 15036),
    "Upgrade to Wall & Tower - Space": (14, "Capitol", "but_upgrade wall and tower", 14, 15011),
    "Zero-G Engineer": (14, "University", "but_zeroengineering_15t", 14, 15024),
}

# The byte a node's own state uses to record that it has been researched.
RESEARCHED_OFFSET = 0x04

TECH_MIN_EPOCH: dict[str, int] = {
    name: epoch for name, (epoch, _b, _t, _n, _i) in TECHNOLOGIES.items()
}

TECH_BUILDING: dict[str, str] = {
    name: building for name, (_e, building, _t, _n, _i) in TECHNOLOGIES.items()
}

# (texture, node epoch) -> name. That pair identifies a node. The
# texture alone isn't unique.
TECH_BY_NODE: dict[tuple[str, int], str] = {
    (texture, node_epoch): name
    for name, (_e, _b, texture, node_epoch, _i) in TECHNOLOGIES.items()
}

# Every effect id the seed may withhold. Baked in so the client can
# publish it the moment it attaches — waiting for a match to read them
# lost the opening research burst every time.
TECH_EFFECT_IDS: tuple[int, ...] = tuple(sorted(
    effect_id for (_e, _b, _t, _n, effect_id) in TECHNOLOGIES.values()
    if effect_id
))
