"""Which technology a technology's effect makes available.

Generated by tools/gen_tech_unlocks.py from the running game's effect
tables. Don't edit by hand.

Researching a technology opens the next tier of its chain, and
`technology_checks` withholds that effect until the `Tech:` item
arrives — so the successor stays unavailable until then. A rule that
doesn't know this hides an item behind a check you need that item to
reach, which is how a run ended stuck in the Bronze Age with
`Epoch: Dark Age` sitting on a Fortress it could not unlock.

Read out of the game rather than guessed. The database says nothing
about chains, and only the wall and tower line gives itself away, by
sharing one icon across seven tiers.
"""

# technology -> the technologies its effect makes researchable
TECH_UNLOCKS: dict[str, tuple[str, ...]] = {
    'Amalgamation': ('Steam Engine',),
    'Ancestor Worship': ('Monotheism',),
    'Anesthesia': ('Magnetic Resonance Imaging',),
    'Basic Oxygen Furnace': ('Core Mining',),
    'Bulls-Eye Lantern': ('Gas Lamps',),
    'Ceremonial Burial': ('Inquisition',),
    'Chemical Drugs': ('Vaccinations',),
    'Civil Liberties': ('Digital Library',),
    'Cofferdam': ('Dry Dock',),
    'Comparative Anatomy': ('Human Anatomy',),
    'Crusades': ('Sunday School',),
    'DNA Research': ('Genetic Engineering',),
    'Dry Dock': ('Scuba Repairs',),
    'Enclosure': ('Pesticides',),
    'Environmental Law': ('Self Sufficiency',),
    'Excommunication': ('Reformation',),
    'Falconry': ('Land Conservation',),
    'Fine-Edged Tools': ('Falconry',),
    'Forestry': ('Mechanized Logging',),
    'Hafted Tools': ('Windlass',),
    'Hand Axe': ('Iron Saw',),
    'Hardened Chisel': ('Shaft Mining',),
    'Herbal Medicines': ('Comparative Anatomy',),
    'Hippocratic Oath': ('Quarantine',),
    'Human Anatomy': ('Pasteurization',),
    'Hydraulic Mining': ('Atom Manipulation',),
    'Hydroponics': ('Robotic Farm',),
    'Indulgences': ('Radio Services',),
    'Inquisition': ('Religious Tolerance',),
    'Iron Saw': ('Forestry',),
    'Irrigation': ('Wheeled Plow',),
    'Land Conservation': ('Environmental Law',),
    'Law Schools': ('Scientific Method',),
    'Metal Casting': ('Amalgamation',),
    'Mining Explosives': ('Basic Oxygen Furnace',),
    'Monotheism': ('Crusades',),
    'Mysticism': ('Prophecy',),
    'Mythology': ('Indulgences',),
    'Occultism': ('Quantum Theology',),
    'Oil Lamp': ('Bulls-Eye Lantern',),
    'Oracle': ('Tarot',),
    'Orthopedics': ('Vitamins',),
    'Pasteurization': ('DNA Research',),
    'Pesticides': ('Hydroponics',),
    'Pharmacy': ('Orthopedics',),
    'Philosophy': ('Law Schools',),
    'Polytheism': ('Excommunication',),
    'Prophecy': ('Occultism',),
    'Pulley': ('Strengthened Concrete',),
    'Quarantine': ('Anesthesia',),
    'Radio Services': ('Virtual Services',),
    'Reformation': ('Televangelism',),
    'Religious Resurgence': ('Faith Healing',),
    'Religious Tolerance': ('Religious Resurgence',),
    'Sainthood': ('Astrology',),
    'Sandals': ('Oracle',),
    'Sanitation': ('Chemical Drugs',),
    'Scientific Method': ('Civil Liberties',),
    'Shaft Mining': ('Mining Explosives',),
    'Shamanism': ('Sainthood',),
    'Steam Engine': ('Hydraulic Mining',),
    'Strengthened Concrete': ('Building Codes',),
    'Upgrade to Wall & Tower - Bronze': ('Upgrade to Wall & Tower - Medieval',),
    'Upgrade to Wall & Tower - Concrete': ('Upgrade to Wall & Tower - Laser',),
    'Upgrade to Wall & Tower - Copper': ('Upgrade to Wall & Tower - Bronze',),
    'Upgrade to Wall & Tower - Imperial': ('Upgrade to Wall & Tower - Concrete',),
    'Upgrade to Wall & Tower - Laser': ('Upgrade to Wall & Tower - Space',),
    'Upgrade to Wall & Tower - Medieval': ('Upgrade to Wall & Tower - Imperial',),
    'Vaccinations': ('Anti-Aging Pill',),
    'Vitamins': ('Cybernetics',),
    'Wheeled Plow': ('Enclosure',),
    'Windlass': ('Hammer Drilling Rigs',),
}

# The reverse: technology -> the technology whose `Tech:` item has to
# arrive before its button exists.
TECH_REQUIRES: dict[str, str] = {
    later: earlier
    for earlier, opened in TECH_UNLOCKS.items()
    for later in opened
}
