"""Which units share a build-menu position.

Built by tools/build_unit_slots.py from the observed listings in
tools/data. Don't edit by hand.

A building's menu is a fixed row of positions, one per line, showing
the one unit of that line valid in this epoch. A unit retires and the
next takes its position, so the check for a retired unit has to be
carried by whatever takes its slot — not by whatever the upgrade chain
calls its replacement. The two differ: slot 4 of the Barracks runs
Viking to Hand Cannoneer to Heavy Mortar and no upgrade connects any
of them.
"""

# building -> slots, each earliest occupant first, by database name
UNIT_SLOTS: dict[str, tuple[tuple[str, ...], ...]] = {
    'Airport': (('a Strafe Fighter11 ME262', 'a Strafe Fighter12 Stealth Fighter', 'a Strafe Fighter13 Talon', 'a Strafe Fighter14 Phoenix',), ('a Strafe Fighter10 Fokker DR.1', 'a Fighter11 P51', 'a Fighter12 F-15', 'a Fighter13 F-48 Jackal', 'a Fighter14 F-96 Nebula',), ('a Fighter10 Sopwith Camel F.1',), ('a Bomber 11 B-17', 'a Bomber 12 Stealth B-2', 'a Bomber 13 B-122 Wyvern',), ('a Bomber 10 Gotha', 'a BomberNuc11 B-29', 'a BomberNuc12 B-52', 'a BomberNuc13 Titan',), ('a AT Fighter11 Typhoon', 'a AT Fighter12 A-10', 'a Helicopter Sea King II 13',), ('a Helicopter Sea King 12', 'a HelicopterXprt13 Pegasus',), ('a HelicopterXprt12 Chinook Transport 12', 'a HelicopterXprt13 Pegasus', 'a HelicopterAT13 Spectre',), ('a Helicopter Apache Longbow 12', 'a HelicopterAT13 Spectre', 'a HelicopterGunShip13 Reaper',), ('a HelicopterGunShip12 Gun Ship', 'a HelicopterGunShip13 Reaper',), ('a Fighter15 Planetary Fighter',),),
    'Archery Range': (('Inf04 - Javelin', 'Inf05 - Pilum',), ('Arch02 - Slinger', 'Arch03 - Simple Bowman', 'Arch05 - Composite Bow', 'Arch06 - Long Bow',), ('Arch04 - Chariot Archer', 'Arch06 - Cavalry Archer',), ('Arch04 - Elephant Archer',), ('Arch05 - Cross Bow',),),
    'Barracks': (('Inf01 - Rock Thrower', 'Inf07 - Arquebus', 'Inf08 - Musketeer', 'Inf09 - Grenadier', 'Inf10 - Doughboy', 'Inf11 - Marine', 'Inf13 - Sentinel', 'Inf14 - Guardian', 'Inf15 - Watchman',), ('Inf01 - Clubman', 'Inf03 - Maceman', 'Inf04 - Short Sword', 'Inf06 - LongSword', 'Inf09 - Partisan',), ('Inf02 - Spearman', 'Inf04 - Phalanx', 'Inf06 - Pikeman', 'Inf08 - Halberdier', 'Inf10 - Grenade Launcher', 'Inf11 - Bazooka Infantry',), ('Inf02 - Sampson', 'Inf05 - Viking', 'Inf08 - Hand Cannoneer', 'Inf10 - Trench Mortar', 'Inf12 - Heavy Mortar',), ('Inf05 - Barbarian', 'Inf08 - Sharpshooter', 'Inf10 - Sniper',), ('Field Medic - Imperial', 'Field Medic WWII', 'Field Medic 13',), ('Inf09 - Elite Guard', 'AA10 - Stinger Soldier',), ('Inf10 - Machine Gun',), ('Inf11 - Flame Thrower',),),
    'Capitol': (('Citizen',), ('Domestic Wolf',), ('h1-3 Sargon of Akkad (heal)', 'h1-4 Alexander the Great (heal)', 'h1-5 Charlemagne (heal)', 'h1 6 William the Conqueror (heal)', 'h1-7 Isabella (heal)', 'h1-8 Elizabeth I (heal)', 'h1-9 Otto Von Bismarck (heal)', 'h1-10 DeVerran (heal)', 'h1-11 Rommel (heal)', 'h1-12 R.W. Bresden (heal)', 'h1-13 Alexi Septimus (heal)', 'h1-14 Molly Ryan (heal)', 'h1 - 15 Khan Sun Do (Strategist)',), ('h2-3 Gilgamesh (Morale)', 'h2-4 Hannibal (Morale)', 'h2-5 Julius Caesar (Morale)', 'h2-6 Richard the Lionheart (Morale)', 'h2-7 Henry V (Morale)', 'h2-8 Oliver Cromwell (Morale)', 'h2-9 Napoleon (Morale)', 'h2-10 von Richtofen (Morale)', 'h2-11 Shackelford (Morale)', 'h2-12 St. Albans (Morale)', 'h2-13 Sergei Molotov (Morale)', 'h2-14 Cyborg Molotov (Morale)', 'h2 - 15 Hu Kwan Do (Warrior)',), ('a Balloon09 Hot Air Balloon', 'a Balloon10 Observation Balloon',),),
    'Cyber Factory': (('Mech Hyperion', 'Mech Hyperion II',), ('Mech Ares', 'Mech Ares II',), ('Mech Pandora', 'Mech Pandora II',), ('Mech Minotaur', 'Mech Minotaur II',), ('Mech Zeus',),),
    'Cyber Laboratory': (('Mech Apollo',), ('Mech Furies',), ('Mech Tempest',), ('Mech Hades',), ('Mech Poseidon',),),
    'Dock': (('s02 Fishing Boat Stone', 's04 Fishing Boat Bronze', 's08 Fishing Boat Imperial', 's11 Fishing Boat Modern', 's13 Digital Fishing Boat',), ('s02 Stone Transport', 's03 Copper Transport', 's04 Bronze Transport', 's08 Imperial Transport', 's10 Atomic Age Transport', 's13 Gargantua Transport',), ('s03 Copper Battleship [Galley]', 's04 Bronze Battleship [Pentakonter]', 's05 Byzantine Battleship [Septrireme]', 's06 Middle Ages Battleship [Decereme]', 's07 Renaissance Battleship [Galleon]', 's08 Imperial Battleship', 's09 Royal Battleship', 's10 Dreadnought Battleship', 's11 Bismarck Battleship', 's13 Leviathon Battleship',), ('s02 Stone Frigate [War Raft]', 's03 Copper Frigate', 's04 Bronze Frigate', 's05 Byzantine Frigate', 's06 Middle Age Frigate', 's07 Renaissance Frigate', 's08 Imperial Frigate', 's09 Royal Frigate', 's10 Good Hope Frigate', 's11 Warrington', 's13 Juggernaut Frigate',), ('s03 Copper Galley', 's04 Bronze Galley', 's05 Byzantine Galley', 's06 Middle Age Galley', 's07 Renaissance Galleon', 's08 Imperial Galleon', 's09 Royal Galleon',), ('s08 Gunboat Cruiser', 's10 Cruiser', 's13 Sagitarian Cruiser',),),
    'Naval Yard': (('s10 U Boat', 's12 Nautilus Submarine', 's14 Hammerhead Submarine',), ('s11 Enterprise Aircraft Carrier', 's13 Nexus Carrier',), ('s12 Trident Submarine', 's14 Triton Submarine',), ('a Helicopter Sea King 12', 'a Helicopter Sea King II 13',),),
    'Siege Factory': (('Gun Spear04 Stone Thrower', 'Gun Spear06 Balistae',), ('x Ram ME', 'Siege06 - Heavy Ram',), ('x Catapult - ME', 'Gun Siege06 Trebuchet',), ('Siege04 - Tower', 'Siege06 - Heavy Tower',), ('Gun Cannon07 - Culverin Cannon', 'Gun Cannon09 - Bronze Cannon',), ('Gun Siege07 Basilisk Cannon', 'Gun Siege09 Serpentine Cannon', 'Gun Siege10 Howitzer Cannon', 'Gun Siege13 Paladin Cannon',), ('Gun Artillery08 Bombard', 'Gun Artillery10 Artillery', 'Gun Artillery13 Colossus',), ('Gun AT10 57mm AT Gun', 'Gun AT12 120mm At Gun', 'Gun AT13 Thor AT Gun', 'Gun AT14 Hercules AT Gun',),),
    'Space Dock': (('Sp15 - Capital Ship',), ('Sp15 - Space Carrier',), ('Sp15 - Space Transport',), ('Sp15 - Space Corvette',),),
    'Stable': (('Cav07 - Carabineers (gun)', 'Cav09 - Dragoon (gun)',), ('Cav03 - Horseman', 'Cav05 - Cataphract', 'Cav07 - Royal Cuirassier (Sword)', 'Cav09 - Imperial Cuirassier Sword',), ('Cav04 - Bronze Spear Cavalry', 'Cav06 - Knight',), ('Cav04 - War Elephant',), ('Cav05 Persian Cavalry',),),
    'Tank Factory': (('Tank10  Mk V', 'Tank11 Sherman', 'Tank12  M1A1', 'Tank13 Gladiator', 'Tank14 Centurion',), ('Tank10 A7V', 'Tank11 Panzer', 'Tank12 Leopard',), ('10 AA - Tank', '13 AA Tank Skywatcher',), ('14 Anti Missile Battery',),),
    'Temple': (('Priest',), ('Prophet',),),
}

# unit -> the epoch it has to stay buildable through, because nothing
# takes its menu position until then. 15 means nothing ever does. See
# the note in this file's generator; without it the check closes and
# logic never knows.
SLOT_GAPS: dict[str, int] = {
    'Arch04 - Elephant Archer': 15,
    'Cav04 - War Elephant': 15,
    'Cav05 Persian Cavalry': 15,
    'Cav06 - Knight': 15,
    'Gun Cannon09 - Bronze Cannon': 15,
    'Gun Siege06 Trebuchet': 15,
    'Gun Spear06 Balistae': 15,
    'Inf01 - Rock Thrower': 5,
    'Inf02 - Sampson': 3,
    'Inf05 - Barbarian': 6,
    'Inf05 - Pilum': 15,
    'Inf05 - Viking': 6,
    'Inf06 - LongSword': 7,
    'Inf09 - Elite Guard': 10,
    'Inf09 - Partisan': 15,
    'Inf10 - Machine Gun': 15,
    'Inf10 - Sniper': 15,
    'Inf11 - Bazooka Infantry': 15,
    'Inf11 - Flame Thrower': 15,
    'Siege06 - Heavy Ram': 15,
    'Siege06 - Heavy Tower': 15,
    'Tank12 Leopard': 15,
    'a Balloon09 Hot Air Balloon': 15,
    'a Balloon10 Observation Balloon': 15,
    'a Fighter10 Sopwith Camel F.1': 15,
    'a HelicopterGunShip13 Reaper': 15,
    's09 Royal Galleon': 15,
}

# unit -> the earliest epoch any menu draws it. `Locations` takes this
# against the database's own figure and keeps the later one.
SLOT_FIRST_EPOCH: dict[str, int] = {
    '10 AA - Tank': 9,
    '13 AA Tank Skywatcher': 12,
    '14 Anti Missile Battery': 12,
    'AA10 - Stinger Soldier': 11,
    'Arch02 - Slinger': 1,
    'Arch03 - Simple Bowman': 2,
    'Arch04 - Chariot Archer': 3,
    'Arch04 - Elephant Archer': 3,
    'Arch05 - Composite Bow': 4,
    'Arch05 - Cross Bow': 4,
    'Arch06 - Cavalry Archer': 5,
    'Arch06 - Long Bow': 5,
    'Cav03 - Horseman': 2,
    'Cav04 - Bronze Spear Cavalry': 3,
    'Cav04 - War Elephant': 3,
    'Cav05 - Cataphract': 4,
    'Cav05 Persian Cavalry': 4,
    'Cav06 - Knight': 5,
    'Cav07 - Carabineers (gun)': 6,
    'Cav07 - Royal Cuirassier (Sword)': 6,
    'Cav09 - Dragoon (gun)': 8,
    'Cav09 - Imperial Cuirassier Sword': 8,
    'Citizen': 0,
    'Domestic Wolf': 0,
    'Field Medic - Imperial': 7,
    'Field Medic 13': 12,
    'Field Medic WWII': 9,
    'Gun AT10 57mm AT Gun': 9,
    'Gun AT12 120mm At Gun': 11,
    'Gun AT13 Thor AT Gun': 12,
    'Gun AT14 Hercules AT Gun': 13,
    'Gun Artillery08 Bombard': 7,
    'Gun Artillery10 Artillery': 9,
    'Gun Artillery13 Colossus': 12,
    'Gun Cannon07 - Culverin Cannon': 6,
    'Gun Cannon09 - Bronze Cannon': 8,
    'Gun Siege06 Trebuchet': 5,
    'Gun Siege07 Basilisk Cannon': 6,
    'Gun Siege09 Serpentine Cannon': 8,
    'Gun Siege10 Howitzer Cannon': 9,
    'Gun Siege13 Paladin Cannon': 12,
    'Gun Spear04 Stone Thrower': 3,
    'Gun Spear06 Balistae': 5,
    'Inf01 - Clubman': 0,
    'Inf01 - Rock Thrower': 0,
    'Inf02 - Sampson': 1,
    'Inf02 - Spearman': 1,
    'Inf03 - Maceman': 2,
    'Inf04 - Javelin': 3,
    'Inf04 - Phalanx': 3,
    'Inf04 - Short Sword': 3,
    'Inf05 - Barbarian': 4,
    'Inf05 - Pilum': 4,
    'Inf05 - Viking': 4,
    'Inf06 - LongSword': 5,
    'Inf06 - Pikeman': 5,
    'Inf07 - Arquebus': 6,
    'Inf08 - Halberdier': 7,
    'Inf08 - Hand Cannoneer': 7,
    'Inf08 - Musketeer': 7,
    'Inf08 - Sharpshooter': 7,
    'Inf09 - Elite Guard': 7,
    'Inf09 - Grenadier': 8,
    'Inf09 - Partisan': 8,
    'Inf10 - Doughboy': 9,
    'Inf10 - Grenade Launcher': 9,
    'Inf10 - Machine Gun': 9,
    'Inf10 - Sniper': 9,
    'Inf10 - Trench Mortar': 9,
    'Inf11 - Bazooka Infantry': 10,
    'Inf11 - Flame Thrower': 10,
    'Inf11 - Marine': 10,
    'Inf12 - Heavy Mortar': 11,
    'Inf13 - Sentinel': 12,
    'Inf14 - Guardian': 13,
    'Inf15 - Watchman': 14,
    'Mech Apollo': 12,
    'Mech Ares': 12,
    'Mech Ares II': 13,
    'Mech Furies': 12,
    'Mech Hades': 13,
    'Mech Hyperion': 12,
    'Mech Hyperion II': 13,
    'Mech Minotaur': 12,
    'Mech Minotaur II': 13,
    'Mech Pandora': 12,
    'Mech Pandora II': 13,
    'Mech Poseidon': 13,
    'Mech Tempest': 12,
    'Mech Zeus': 13,
    'Priest': 1,
    'Prophet': 1,
    'Siege04 - Tower': 3,
    'Siege06 - Heavy Ram': 5,
    'Siege06 - Heavy Tower': 5,
    'Sp15 - Capital Ship': 14,
    'Sp15 - Space Carrier': 14,
    'Sp15 - Space Corvette': 14,
    'Sp15 - Space Transport': 14,
    'Tank10  Mk V': 9,
    'Tank10 A7V': 9,
    'Tank11 Panzer': 10,
    'Tank11 Sherman': 10,
    'Tank12  M1A1': 11,
    'Tank12 Leopard': 11,
    'Tank13 Gladiator': 12,
    'Tank14 Centurion': 13,
    'a AT Fighter11 Typhoon': 10,
    'a AT Fighter12 A-10': 11,
    'a Balloon09 Hot Air Balloon': 8,
    'a Balloon10 Observation Balloon': 9,
    'a Bomber 10 Gotha': 9,
    'a Bomber 11 B-17': 10,
    'a Bomber 12 Stealth B-2': 11,
    'a Bomber 13 B-122 Wyvern': 12,
    'a BomberNuc11 B-29': 10,
    'a BomberNuc12 B-52': 11,
    'a BomberNuc13 Titan': 12,
    'a Fighter10 Sopwith Camel F.1': 9,
    'a Fighter11 P51': 10,
    'a Fighter12 F-15': 11,
    'a Fighter13 F-48 Jackal': 12,
    'a Fighter14 F-96 Nebula': 13,
    'a Fighter15 Planetary Fighter': 14,
    'a Helicopter Apache Longbow 12': 11,
    'a Helicopter Sea King 12': 11,
    'a Helicopter Sea King II 13': 13,
    'a HelicopterAT13 Spectre': 12,
    'a HelicopterGunShip12 Gun Ship': 11,
    'a HelicopterGunShip13 Reaper': 12,
    'a HelicopterXprt12 Chinook Transport 12': 11,
    'a HelicopterXprt13 Pegasus': 12,
    'a Strafe Fighter10 Fokker DR.1': 9,
    'a Strafe Fighter11 ME262': 10,
    'a Strafe Fighter12 Stealth Fighter': 11,
    'a Strafe Fighter13 Talon': 12,
    'a Strafe Fighter14 Phoenix': 13,
    'h1 - 15 Khan Sun Do (Strategist)': 14,
    'h1 6 William the Conqueror (heal)': 5,
    'h1-10 DeVerran (heal)': 9,
    'h1-11 Rommel (heal)': 10,
    'h1-12 R.W. Bresden (heal)': 11,
    'h1-13 Alexi Septimus (heal)': 12,
    'h1-14 Molly Ryan (heal)': 13,
    'h1-3 Sargon of Akkad (heal)': 2,
    'h1-4 Alexander the Great (heal)': 3,
    'h1-5 Charlemagne (heal)': 4,
    'h1-7 Isabella (heal)': 6,
    'h1-8 Elizabeth I (heal)': 7,
    'h1-9 Otto Von Bismarck (heal)': 8,
    'h2 - 15 Hu Kwan Do (Warrior)': 14,
    'h2-10 von Richtofen (Morale)': 9,
    'h2-11 Shackelford (Morale)': 10,
    'h2-12 St. Albans (Morale)': 11,
    'h2-13 Sergei Molotov (Morale)': 12,
    'h2-14 Cyborg Molotov (Morale)': 13,
    'h2-3 Gilgamesh (Morale)': 2,
    'h2-4 Hannibal (Morale)': 3,
    'h2-5 Julius Caesar (Morale)': 4,
    'h2-6 Richard the Lionheart (Morale)': 5,
    'h2-7 Henry V (Morale)': 6,
    'h2-8 Oliver Cromwell (Morale)': 7,
    'h2-9 Napoleon (Morale)': 8,
    's02 Fishing Boat Stone': 1,
    's02 Stone Frigate [War Raft]': 1,
    's02 Stone Transport': 1,
    's03 Copper Battleship [Galley]': 2,
    's03 Copper Frigate': 2,
    's03 Copper Galley': 2,
    's03 Copper Transport': 2,
    's04 Bronze Battleship [Pentakonter]': 3,
    's04 Bronze Frigate': 3,
    's04 Bronze Galley': 3,
    's04 Bronze Transport': 3,
    's04 Fishing Boat Bronze': 3,
    's05 Byzantine Battleship [Septrireme]': 4,
    's05 Byzantine Frigate': 4,
    's05 Byzantine Galley': 4,
    's06 Middle Age Frigate': 5,
    's06 Middle Age Galley': 5,
    's06 Middle Ages Battleship [Decereme]': 5,
    's07 Renaissance Battleship [Galleon]': 6,
    's07 Renaissance Frigate': 6,
    's07 Renaissance Galleon': 6,
    's08 Fishing Boat Imperial': 7,
    's08 Gunboat Cruiser': 7,
    's08 Imperial Battleship': 7,
    's08 Imperial Frigate': 7,
    's08 Imperial Galleon': 7,
    's08 Imperial Transport': 7,
    's09 Royal Battleship': 8,
    's09 Royal Frigate': 8,
    's09 Royal Galleon': 8,
    's10 Atomic Age Transport': 9,
    's10 Cruiser': 9,
    's10 Dreadnought Battleship': 9,
    's10 Good Hope Frigate': 9,
    's10 U Boat': 9,
    's11 Bismarck Battleship': 10,
    's11 Enterprise Aircraft Carrier': 10,
    's11 Fishing Boat Modern': 10,
    's11 Warrington': 10,
    's12 Nautilus Submarine': 11,
    's12 Trident Submarine': 11,
    's13 Digital Fishing Boat': 12,
    's13 Gargantua Transport': 12,
    's13 Juggernaut Frigate': 12,
    's13 Leviathon Battleship': 12,
    's13 Nexus Carrier': 12,
    's13 Sagitarian Cruiser': 12,
    's14 Hammerhead Submarine': 13,
    's14 Triton Submarine': 13,
    'x Catapult - ME': 3,
    'x Ram ME': 3,
}

# unit -> every unit that held its slot before it, so the current
# occupant sends all of their checks.
SLOT_PREDECESSORS: dict[str, tuple[str, ...]] = {
    unit: tuple(seat[:i])
    for seats in UNIT_SLOTS.values()
    for seat in seats
    for i, unit in enumerate(seat)
    if i
}
