"""Write BuildingEpochs.py: the epoch each building actually unlocks in.

The epoch field in `dbobjects.dat` is not the epoch the game uses. It reads one
higher for most buildings and two higher for the Temple, so it is not even a
consistent offset that could be corrected in place. Taken at face value it puts
a Granary in the Bronze Age when the game offers it in the Copper Age, and that
error propagates into technology floors, because a technology cannot be
researched before the building that researches it exists.

The tech tree node knows the truth: `node + 0x14` is compared against the tech
tree's current epoch by the availability predicate itself, so it is the number
the game actually gates on. This reads it for every building and writes it out.

Run once with Empire Earth open, in a match; after that the generated module is
committed and generation never needs the game again.

    py tools\\gen_building_epochs.py           # rewrite BuildingEpochs.py
    py tools\\gen_building_epochs.py --check   # report without writing
"""

from __future__ import annotations

import os
import sys
import types

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "world", "empire_earth"))

_f = types.ModuleType("BaseClasses")


class _IC:
    progression = "p"
    filler = "f"
    useful = "u"


_f.ItemClassification = _IC
_f.Item = object
_f.Location = object
sys.modules.setdefault("BaseClasses", _f)

from Addresses import ResourceAccess, profile_for      # noqa: E402
from BuildingGate import BuildingGate                  # noqa: E402
from Epochs import EPOCH_NAMES, EpochAccess            # noqa: E402
from Items import _ALL_BUILDINGS                       # noqa: E402
from Memory import attach                              # noqa: E402
from Objects import BUILDING_MIN_EPOCH                 # noqa: E402
from Roster import Roster                              # noqa: E402

OUT = os.path.join(ROOT, "world", "empire_earth", "BuildingEpochs.py")

NODE_EPOCH = 0x14


def main():
    proc = attach("EE-AOC.exe")
    if proc is None:
        sys.exit("Empire Earth is not running")
    prof = profile_for("EE-AOC.exe")
    epochs = EpochAccess(proc, ResourceAccess(proc, prof))
    gate = BuildingGate(proc, Roster(proc, prof), epochs)

    nodes = gate.scan(_ALL_BUILDINGS)
    if not nodes:
        sys.exit("no tech tree nodes found - are you in a match?")

    found, missing = {}, []
    for building in _ALL_BUILDINGS:
        addrs = nodes.get(building)
        if not addrs:
            missing.append(building)
            continue
        # A building with several nodes has late variants; the earliest is the
        # one that decides when it first becomes available.
        found[building] = min(
            proc.read_i32(a + NODE_EPOCH) or 0 for a in addrs
        )

    print(f"{len(found)}/{len(_ALL_BUILDINGS)} buildings read from the tech tree")
    for building in _ALL_BUILDINGS:
        if building not in found:
            continue
        was = BUILDING_MIN_EPOCH.get(building)
        now = found[building]
        flag = "" if was == now else f"   <- database said {was}"
        print(f"   {building:<18s} {now:>2d}  {EPOCH_NAMES[now]:<20s}{flag}")
    if missing:
        print(f"\nno node found for: {missing}")
        print("(these keep their database epoch)")

    if "--check" in sys.argv:
        print("\n--check: not written")
        return

    lines = [
        '"""The epoch each building actually unlocks in.',
        "",
        "Generated by tools/gen_building_epochs.py from a running game; do not",
        "edit by hand.",
        "",
        "`dbobjects.dat` disagrees, and not by a constant: it reads one higher",
        "for most buildings and two higher for the Temple. The number here is",
        "`node + 0x14`, which is what the availability predicate compares",
        "against the current epoch, so it is what the game gates on.",
        '"""',
        "",
        "BUILDING_EPOCH: dict[str, int] = {",
    ]
    for building in _ALL_BUILDINGS:
        if building in found:
            lines.append(f'    "{building}": {found[building]},')
    lines += ["}", ""]
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
